# config/settings.yaml
app:
  name: "我的脚本工具"

# 文件整理配置
file_organizer:
  images: ['.jpg', '.jpeg', '.png', '.gif', '.bmp', '.svg', '.webp']
  documents: ['.pdf', '.doc', '.docx', '.txt', '.rtf', '.odt']
  videos: ['.mp4', '.avi', '.mkv', '.mov', '.wmv', '.flv']
  audio: ['.mp3', '.wav', '.flac', '.aac', '.ogg']
  code: ['.py', '.js', '.html', '.css', '.java', '.cpp', '.c']
  archives: ['.zip', '.rar', '.7z', '.tar', '.gz']
  spreadsheets: ['.xls', '.xlsx', '.csv', '.ods']

# 日志清理配置
log_cleaner:
  keep_days: 30
  log_dirs: ['./logs']
